### ISSUE TITLE
page_view.ex module PhoenixMaru.Router.Helpers is not loaded and could not be found

### ISSUE THREAD

**Issue by peterwillcn** [elixir-maru/maru_examples#6]
==> phoenix_maru
Compiling 16 files (.ex)

== Compilation error on file web/views/page_view.ex ==
** (CompileError) web/views/page_view.ex:2: module PhoenixMaru.Router.Helpers is not loaded and could not be found
    expanding macro: PhoenixMaru.Web.__using__/1
    web/views/page_view.ex:2: PhoenixMaru.PageView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/page_view.ex:2: PhoenixMaru.PageView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

**Comment by Cifer-Y** [comment]
@peterwillcn 
What's your elixir version, maru version and phoenix version?
